openapi: 3.0.0
info:
  title: Payment
  version: '1.0'
  description: |
    These are the API for the (version =?)
    This API is a standard REST-style API that accepts /returns JSON requests and is located at :
    http://payment.walliitools.com/
  contact: {}
  license: {}
servers:
  - url: 'http://payment.walliitools.com/Payment'
    description: prod
paths:
  /SetKeys:
    post:
      summary: Set Keys
      operationId: post-SetKeys
      responses:
        '200':
          description: OK
      description: |-
        This method is used to set the keys of payment gateways in the api. Set the keys before every
        call of any method.
      tags:
        - Set Keys
      parameters:
        - schema:
            type: string
          in: query
          name: SquareAccessToken
        - schema:
            type: string
          in: query
          name: SquareClientID
        - schema:
            type: string
          in: query
          name: SquareClientSecret
        - schema:
            type: string
          in: query
          name: SumupClientID
        - schema:
            type: string
          in: query
          name: SumupClientSecret
        - schema:
            type: string
          in: query
          name: BraintreeMerchantId
        - schema:
            type: string
          in: query
          name: BraintreePublicKey
        - schema:
            type: string
          in: query
          name: BraintreePrivateKey
        - schema:
            type: string
          in: query
          name: BraintreeTokenizationKey
  /GetAuthorizationCode:
    parameters: []
    post:
      summary: Get Authorization Code
      operationId: postGetAuthorizationCode
      responses:
        '200':
          description: Sucess
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples: {}
      description: 'This method is used to redirect to payment gateway Oauth authorize window for getting authorization token. Also, authorization token is sent to this method to be used in web api'
      tags:
        - Authorize
      parameters:
        - schema:
            type: string
          in: query
          name: code
          description: |-
            Authorization code sent by payment
            gateway
            (Required if code is to be set)
        - schema:
            type: string
          in: query
          name: paymentGateway
          description: |-
            Name of payment gateway (i.e Square,
            SumUp)
            (Required if method is called to redirect to
            payment gateway authorize window)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            examples:
              example-1:
                value:
                  code: ''
                  paymentGateway: Square
        description: ''
  /ListCustomers:
    post:
      summary: List Customers
      operationId: post-ListCustomers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                example-1:
                  value:
                    errors: null
                    customers:
                      - id: KFKFRBVVN0ZB56Q90BGZ8DESJW
                        created_at: '2020-06-07T12:47:49.926Z'
                        updated_at: '2020-06-07T12:47:50Z'
                        cards:
                          - id: 'ccof:WZngFGfUsqNtg6Zj4GB'
                            card_brand: VISA
                            last_4: '1111'
                            exp_month: 2
                            exp_year: 2023
                            cardholder_name: farah
                            billing_address:
                              address_line_1: '825 Eighth Avenue, New York'
                              address_line_2: '1860 McOrmond drive '
                              address_line_3: null
                              locality: ontario
                              sublocality: null
                              sublocality_2: null
                              sublocality_3: null
                              administrative_district_level_1: ca
                              administrative_district_level_2: null
                              administrative_district_level_3: null
                              postal_code: '94103'
                              country: zz
                              first_name: null
                              last_name: null
                              organization: null
                            fingerprint: null
                            bin: null
                        given_name: farah
                        family_name: fg
                        nickname: fa
                        company_name: test
                        email_address: apitest@hidata.com
                        address:
                          address_line_1: '1860 McOrmond drive '
                          address_line_2: null
                          address_line_3: null
                          locality: Manhattan
                          sublocality: null
                          sublocality_2: null
                          sublocality_3: null
                          administrative_district_level_1: SK
                          administrative_district_level_2: null
                          administrative_district_level_3: null
                          postal_code: S7S 0A5
                          country: null
                          first_name: null
                          last_name: null
                          organization: null
                        phone_number: null
                        birthday: null
                        reference_id: f123
                        note: test
                        preferences:
                          email_unsubscribed: false
                        groups:
                          - id: X8APPS177BVHY.CARDS_ON_FILE
                            name: Cards on File
                        creation_source: THIRD_PARTY
                    cursor: null
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            examples:
              example-1:
                value:
                  paymentGateway: Square
                  cursor: null
                  sortField: null
                  sortOrder: null
                  MerchantToken: string
                  ApplicationToken: string
        description: ''
      tags:
        - Customers
      description: List all the saved customers
      parameters:
        - schema:
            type: string
          in: query
          name: paymentGateway
          description: |-
            Name of payment gateway (i.e Square,
            Braintree)
          required: true
        - schema:
            type: string
          in: query
          name: cursor
          description: |-
            Pagination page no. Returned by payment
            gateway
        - schema:
            type: string
          in: query
          name: sortField
          description: DEFAULT/CREATED_AT
        - schema:
            type: string
          in: query
          name: sortOrder
          description: DESC/ASC
        - schema:
            type: string
          in: query
          name: MerchantToken
          required: true
        - schema:
            type: string
          in: query
          name: ApplicationToken
          required: true
  /CreateCustomer:
    post:
      summary: Create Customer
      operationId: post-CreateCustomer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                example-1:
                  value:
                    customerID: 3386QC83KGY1FDYDRRWTVDNDVM
      description: Create customer
      tags:
        - Customers
      parameters:
        - schema:
            type: string
          in: query
          name: paymentGateway
          required: true
        - schema:
            type: string
          in: query
          name: CustomerName
          description: Customer name
          required: true
        - schema:
            type: string
          in: query
          name: AddressLine1
          description: Address
          required: true
        - schema:
            type: string
          in: query
          name: AdministrativeDistrictLevel1
          required: true
          description: |-
            Two letter state code formatted
            according to ISO3166-1 alpha-2.
        - schema:
            type: string
          in: query
          name: Locality
          description: Locality name
          required: true
        - schema:
            type: string
          in: query
          name: PostalCode
          description: Postal Code
          required: true
        - schema:
            type: string
          in: query
          name: CompanyName
          description: Name of the customerâ€™s company
          required: true
        - schema:
            type: string
          in: query
          name: EmailAddress
          description: Email address of customer
          required: true
        - schema:
            type: string
          in: query
          name: FamilyName
          description: Family Name
        - schema:
            type: string
          in: query
          name: Nickname
          description: Nick Name
        - schema:
            type: string
          in: query
          name: PhoneNumber
          description: Customer Phone Number
        - schema:
            type: string
          in: query
          name: ReferenceId
          required: true
          description: |-
            Any reference id to uniquely identify the
            customer I.e. CustomerID
        - schema:
            type: string
          in: query
          name: Note
          description: Any Note
        - schema:
            type: string
          in: query
          name: Country
          description: |-
            Two letter country code formatted
            according to ISO3166-1 alpha-2.
          required: true
        - schema:
            type: string
          in: query
          name: Website
          description: Website of customer
        - schema:
            type: string
          in: query
          name: MerchantToken
          required: true
        - schema:
            type: string
          in: query
          name: ApplicationToken
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            examples:
              example-1:
                value:
                  paymentGateway: Square
                  CustomerName: abc
                  AddressLine1: 1881 yonge street
                  AdministrativeDistrictLevel1: ''
                  Locality: toronto
                  PostalCode: M5E 1E5
                  CompanyName: string
                  EmailAddress: abc@gmail.com
                  FamilyName: string
                  Nickname: string
                  PhoneNumber: string
                  ReferenceId: ReferenceId
                  Note: ''
                  Country: Canada
                  Website: www.test.com
                  MerchantToken: MerchantToken
                  ApplicationToken: ApplicationToken
components:
  schemas: {}
  securitySchemes:
    'Application Token, Merchant Token':
      type: http
      scheme: oauth
      description: "Unless otherwise noted all calls to the API use HTTP basic authorization over HTTPS.\nUse MerchantToken and ApplicationToken of the willitools payments  environment as the basic developer for each api as parameter except SetKeys .\n\nApplication Token: is a secret word that we issue to a developer. The APIs check the token to authenticate the developer and provide/deny access to the APIs. If we revoke the token at the server, then the developer will have no access\n \nMerchant Token: is a secret word that we issue to a merchant. The APIs check the token to authenticate the merchant and provide/deny access to the APIs. If we revoke the token at the server, then the merchnat will have no access\n\n"
